import type { Metadata } from "next";
import { Archivo, Geist, Geist_Mono, Gelasio, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { TemplateProvider } from "@/lib/context/TemplateContext";
import { FormDataProvider } from "@/lib/context/FormDataContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const archivo = Archivo({
  subsets: ["latin"],

  variable: "--archivo",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
});

const georgia = Gelasio({
  subsets: ["latin"],
  variable: "--georgia",
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // adjust weights as needed
  variable: '--montserrat',
})





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
                <TemplateProvider>
                    <FormDataProvider>


            {children}
            </FormDataProvider>
            </TemplateProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
